#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 87
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 13

enum ts_symbol_identifiers {
  anon_sym_fn = 1,
  anon_sym_EQ = 2,
  anon_sym_SEMI = 3,
  anon_sym_COLON = 4,
  anon_sym_LPAREN = 5,
  anon_sym_COMMA = 6,
  anon_sym_RPAREN = 7,
  sym_identifier = 8,
  sym_number = 9,
  anon_sym_true = 10,
  anon_sym_false = 11,
  anon_sym_BANG_EQ = 12,
  anon_sym_EQ_EQ = 13,
  anon_sym_LT = 14,
  anon_sym_LT_EQ = 15,
  anon_sym_GT = 16,
  anon_sym_GT_EQ = 17,
  anon_sym_PLUS = 18,
  anon_sym_DASH = 19,
  anon_sym_STAR = 20,
  anon_sym_SLASH = 21,
  anon_sym_LBRACE = 22,
  anon_sym_RBRACE = 23,
  anon_sym_if = 24,
  anon_sym_in = 25,
  anon_sym_else = 26,
  sym_comment = 27,
  sym_program = 28,
  sym__declaration = 29,
  sym_function_declaration = 30,
  sym_argument = 31,
  sym_argument_list = 32,
  sym__expression = 33,
  sym_boolean = 34,
  sym_binary_expression = 35,
  sym_assignment_expression = 36,
  sym_variable_reference = 37,
  sym_variable_declaration = 38,
  sym_grouped_expression = 39,
  sym_block_expression = 40,
  sym_if_expression = 41,
  aux_sym_program_repeat1 = 42,
  aux_sym_argument_list_repeat1 = 43,
  aux_sym_block_expression_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_fn] = "fn",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if",
  [anon_sym_in] = "in",
  [anon_sym_else] = "else",
  [sym_comment] = "comment",
  [sym_program] = "program",
  [sym__declaration] = "_declaration",
  [sym_function_declaration] = "function_declaration",
  [sym_argument] = "argument",
  [sym_argument_list] = "argument_list",
  [sym__expression] = "_expression",
  [sym_boolean] = "boolean",
  [sym_binary_expression] = "binary_expression",
  [sym_assignment_expression] = "assignment_expression",
  [sym_variable_reference] = "variable_reference",
  [sym_variable_declaration] = "variable_declaration",
  [sym_grouped_expression] = "grouped_expression",
  [sym_block_expression] = "block_expression",
  [sym_if_expression] = "if_expression",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_block_expression_repeat1] = "block_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_else] = anon_sym_else,
  [sym_comment] = sym_comment,
  [sym_program] = sym_program,
  [sym__declaration] = sym__declaration,
  [sym_function_declaration] = sym_function_declaration,
  [sym_argument] = sym_argument,
  [sym_argument_list] = sym_argument_list,
  [sym__expression] = sym__expression,
  [sym_boolean] = sym_boolean,
  [sym_binary_expression] = sym_binary_expression,
  [sym_assignment_expression] = sym_assignment_expression,
  [sym_variable_reference] = sym_variable_reference,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_grouped_expression] = sym_grouped_expression,
  [sym_block_expression] = sym_block_expression,
  [sym_if_expression] = sym_if_expression,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_block_expression_repeat1] = aux_sym_block_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_grouped_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_block_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_condition = 1,
  field_else = 2,
  field_initializing_expression = 3,
  field_lhs = 4,
  field_name = 5,
  field_operator = 6,
  field_return_expression = 7,
  field_rhs = 8,
  field_then = 9,
  field_type = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
  [field_else] = "else",
  [field_initializing_expression] = "initializing_expression",
  [field_lhs] = "lhs",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_return_expression] = "return_expression",
  [field_rhs] = "rhs",
  [field_then] = "then",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 1},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 3},
  [11] = {.index = 17, .length = 4},
  [12] = {.index = 21, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_type, 2},
  [2] =
    {field_name, 1},
  [3] =
    {field_return_expression, 1},
  [4] =
    {field_condition, 1},
    {field_then, 2},
  [6] =
    {field_lhs, 0},
    {field_rhs, 2},
  [8] =
    {field_operator, 1},
  [9] =
    {field_initializing_expression, 3},
    {field_name, 0},
  [11] =
    {field_return_expression, 2},
  [12] =
    {field_condition, 1},
    {field_then, 3},
  [14] =
    {field_initializing_expression, 4},
    {field_name, 0},
    {field_type, 2},
  [17] =
    {field_condition, 1},
    {field_else, 3},
    {field_else, 4},
    {field_then, 2},
  [21] =
    {field_condition, 1},
    {field_else, 4},
    {field_else, 5},
    {field_then, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 14,
  [16] = 12,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 17,
  [28] = 18,
  [29] = 19,
  [30] = 20,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 21,
  [36] = 23,
  [37] = 22,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 33,
  [44] = 38,
  [45] = 39,
  [46] = 25,
  [47] = 40,
  [48] = 42,
  [49] = 49,
  [50] = 31,
  [51] = 41,
  [52] = 52,
  [53] = 52,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 72,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 79,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '!', 4,
        '(', 22,
        ')', 24,
        '*', 47,
        '+', 45,
        ',', 23,
        '-', 46,
        '/', 48,
        ':', 21,
        ';', 20,
        '<', 41,
        '=', 19,
        '>', 43,
        'e', 10,
        'f', 5,
        'i', 9,
        't', 12,
        '{', 49,
        '}', 50,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == 'f') ADVANCE(25);
      if (lookahead == 'i') ADVANCE(28);
      if (lookahead == 't') ADVANCE(30);
      if (lookahead == '{') ADVANCE(49);
      if (lookahead == '}') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(24);
      if (lookahead == ',') ADVANCE(23);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '=') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(55);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 9:
      if (lookahead == 'f') ADVANCE(51);
      if (lookahead == 'n') ADVANCE(53);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(6);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(40);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(55);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_program] = STATE(85),
    [sym__declaration] = STATE(60),
    [sym_function_declaration] = STATE(60),
    [aux_sym_program_repeat1] = STATE(60),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    STATE(3), 1,
      aux_sym_block_expression_repeat1,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(54), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [40] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_block_expression_repeat1,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [80] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(30), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(39), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 1,
      anon_sym_RBRACE,
    ACTIONS(44), 1,
      anon_sym_if,
    STATE(4), 1,
      aux_sym_block_expression_repeat1,
    ACTIONS(36), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(56), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [120] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_COLON,
    ACTIONS(47), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(49), 13,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [148] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(47), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(49), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [175] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(57), 13,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [200] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(61), 13,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [225] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(65), 13,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [250] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(69), 13,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [275] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(73), 13,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [300] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_else,
    ACTIONS(75), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(77), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [327] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(83), 13,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [352] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_EQ,
    ACTIONS(95), 1,
      anon_sym_STAR,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(99), 1,
      anon_sym_else,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(89), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(87), 5,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [389] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_EQ,
    ACTIONS(95), 1,
      anon_sym_STAR,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(89), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(87), 6,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [424] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(77), 13,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [449] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_EQ,
    ACTIONS(95), 1,
      anon_sym_STAR,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(103), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 10,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [482] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_EQ,
    ACTIONS(95), 1,
      anon_sym_STAR,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(103), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [513] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_EQ,
    ACTIONS(103), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(101), 13,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [540] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_EQ,
    ACTIONS(95), 1,
      anon_sym_STAR,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(89), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(105), 6,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [575] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_EQ,
    ACTIONS(95), 1,
      anon_sym_STAR,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(89), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(107), 6,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [610] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_EQ,
    ACTIONS(95), 1,
      anon_sym_STAR,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(89), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(109), 6,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [645] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_EQ,
    ACTIONS(95), 1,
      anon_sym_STAR,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(89), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(111), 6,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [680] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(115), 13,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [705] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(119), 1,
      sym_number,
    ACTIONS(121), 1,
      anon_sym_if,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(19), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [739] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(123), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(58), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [773] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_EQ,
    ACTIONS(129), 1,
      anon_sym_STAR,
    ACTIONS(131), 1,
      anon_sym_SLASH,
    ACTIONS(103), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(127), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(101), 9,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [805] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_EQ,
    ACTIONS(129), 1,
      anon_sym_STAR,
    ACTIONS(131), 1,
      anon_sym_SLASH,
    ACTIONS(103), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [835] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_EQ,
    ACTIONS(103), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(101), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [861] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_EQ,
    ACTIONS(129), 1,
      anon_sym_STAR,
    ACTIONS(131), 1,
      anon_sym_SLASH,
    ACTIONS(127), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(135), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(133), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(105), 5,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [895] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(137), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(35), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [929] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(139), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(37), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [963] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(141), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(13), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [997] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(143), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1031] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_EQ,
    ACTIONS(129), 1,
      anon_sym_STAR,
    ACTIONS(131), 1,
      anon_sym_SLASH,
    ACTIONS(127), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(135), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(133), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(107), 5,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [1065] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_EQ,
    ACTIONS(129), 1,
      anon_sym_STAR,
    ACTIONS(131), 1,
      anon_sym_SLASH,
    ACTIONS(127), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(135), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(133), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(111), 5,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [1099] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_EQ,
    ACTIONS(129), 1,
      anon_sym_STAR,
    ACTIONS(131), 1,
      anon_sym_SLASH,
    ACTIONS(127), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(135), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(133), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(109), 5,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [1133] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(145), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1167] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(147), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(28), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1201] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(149), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1235] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_if,
    ACTIONS(151), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1269] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(153), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(53), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1303] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_if,
    ACTIONS(141), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(13), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1337] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_if,
    ACTIONS(155), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1371] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_if,
    ACTIONS(157), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(18), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1405] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(29), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1439] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_if,
    ACTIONS(161), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1473] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(163), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1507] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_if,
    ACTIONS(165), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(57), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1541] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_if,
    ACTIONS(167), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1575] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_if,
    ACTIONS(169), 1,
      sym_number,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(14), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1609] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(125), 1,
      anon_sym_EQ,
    ACTIONS(129), 1,
      anon_sym_STAR,
    ACTIONS(131), 1,
      anon_sym_SLASH,
    ACTIONS(171), 1,
      anon_sym_in,
    STATE(12), 1,
      sym_block_expression,
    ACTIONS(127), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(135), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(133), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1645] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(125), 1,
      anon_sym_EQ,
    ACTIONS(129), 1,
      anon_sym_STAR,
    ACTIONS(131), 1,
      anon_sym_SLASH,
    ACTIONS(173), 1,
      anon_sym_in,
    STATE(16), 1,
      sym_block_expression,
    ACTIONS(127), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(135), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(133), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1681] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_EQ,
    ACTIONS(129), 1,
      anon_sym_STAR,
    ACTIONS(131), 1,
      anon_sym_SLASH,
    ACTIONS(175), 1,
      anon_sym_SEMI,
    ACTIONS(177), 1,
      anon_sym_RBRACE,
    ACTIONS(127), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(135), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(133), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1714] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_EQ,
    ACTIONS(129), 1,
      anon_sym_STAR,
    ACTIONS(131), 1,
      anon_sym_SLASH,
    ACTIONS(175), 1,
      anon_sym_SEMI,
    ACTIONS(179), 1,
      anon_sym_RBRACE,
    ACTIONS(127), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(135), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(133), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1747] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_EQ,
    ACTIONS(129), 1,
      anon_sym_STAR,
    ACTIONS(131), 1,
      anon_sym_SLASH,
    ACTIONS(175), 1,
      anon_sym_SEMI,
    ACTIONS(127), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(135), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(133), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1777] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_EQ,
    ACTIONS(129), 1,
      anon_sym_STAR,
    ACTIONS(131), 1,
      anon_sym_SLASH,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    ACTIONS(127), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(135), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(133), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1807] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_EQ,
    ACTIONS(129), 1,
      anon_sym_STAR,
    ACTIONS(131), 1,
      anon_sym_SLASH,
    ACTIONS(183), 1,
      anon_sym_SEMI,
    ACTIONS(127), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(135), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(133), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1837] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 4,
      anon_sym_LPAREN,
      sym_number,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(185), 4,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_if,
  [1853] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(187), 1,
      ts_builtin_sym_end,
    STATE(61), 3,
      sym__declaration,
      sym_function_declaration,
      aux_sym_program_repeat1,
  [1868] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
    ACTIONS(191), 1,
      anon_sym_fn,
    STATE(61), 3,
      sym__declaration,
      sym_function_declaration,
      aux_sym_program_repeat1,
  [1883] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      anon_sym_RPAREN,
    ACTIONS(198), 1,
      sym_identifier,
    STATE(66), 1,
      sym_argument,
  [1899] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      sym_identifier,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      sym_argument,
  [1912] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_argument_list_repeat1,
  [1925] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      sym_identifier,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      sym_argument,
  [1938] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_COMMA,
    ACTIONS(208), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_argument_list_repeat1,
  [1951] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_COMMA,
    ACTIONS(213), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym_argument_list_repeat1,
  [1964] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_LPAREN,
    STATE(77), 1,
      sym_argument_list,
  [1974] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      sym_identifier,
    STATE(71), 1,
      sym_argument,
  [1984] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1992] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2000] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_EQ,
    ACTIONS(221), 1,
      sym_identifier,
  [2010] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_EQ,
    ACTIONS(225), 1,
      sym_identifier,
  [2020] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [2028] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym_identifier,
  [2035] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_EQ,
  [2042] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_EQ,
  [2049] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_RPAREN,
  [2056] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_EQ,
  [2063] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_EQ,
  [2070] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_COLON,
  [2077] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_EQ,
  [2084] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_identifier,
  [2091] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_EQ,
  [2098] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      ts_builtin_sym_end,
  [2105] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 120,
  [SMALL_STATE(6)] = 148,
  [SMALL_STATE(7)] = 175,
  [SMALL_STATE(8)] = 200,
  [SMALL_STATE(9)] = 225,
  [SMALL_STATE(10)] = 250,
  [SMALL_STATE(11)] = 275,
  [SMALL_STATE(12)] = 300,
  [SMALL_STATE(13)] = 327,
  [SMALL_STATE(14)] = 352,
  [SMALL_STATE(15)] = 389,
  [SMALL_STATE(16)] = 424,
  [SMALL_STATE(17)] = 449,
  [SMALL_STATE(18)] = 482,
  [SMALL_STATE(19)] = 513,
  [SMALL_STATE(20)] = 540,
  [SMALL_STATE(21)] = 575,
  [SMALL_STATE(22)] = 610,
  [SMALL_STATE(23)] = 645,
  [SMALL_STATE(24)] = 680,
  [SMALL_STATE(25)] = 705,
  [SMALL_STATE(26)] = 739,
  [SMALL_STATE(27)] = 773,
  [SMALL_STATE(28)] = 805,
  [SMALL_STATE(29)] = 835,
  [SMALL_STATE(30)] = 861,
  [SMALL_STATE(31)] = 895,
  [SMALL_STATE(32)] = 929,
  [SMALL_STATE(33)] = 963,
  [SMALL_STATE(34)] = 997,
  [SMALL_STATE(35)] = 1031,
  [SMALL_STATE(36)] = 1065,
  [SMALL_STATE(37)] = 1099,
  [SMALL_STATE(38)] = 1133,
  [SMALL_STATE(39)] = 1167,
  [SMALL_STATE(40)] = 1201,
  [SMALL_STATE(41)] = 1235,
  [SMALL_STATE(42)] = 1269,
  [SMALL_STATE(43)] = 1303,
  [SMALL_STATE(44)] = 1337,
  [SMALL_STATE(45)] = 1371,
  [SMALL_STATE(46)] = 1405,
  [SMALL_STATE(47)] = 1439,
  [SMALL_STATE(48)] = 1473,
  [SMALL_STATE(49)] = 1507,
  [SMALL_STATE(50)] = 1541,
  [SMALL_STATE(51)] = 1575,
  [SMALL_STATE(52)] = 1609,
  [SMALL_STATE(53)] = 1645,
  [SMALL_STATE(54)] = 1681,
  [SMALL_STATE(55)] = 1714,
  [SMALL_STATE(56)] = 1747,
  [SMALL_STATE(57)] = 1777,
  [SMALL_STATE(58)] = 1807,
  [SMALL_STATE(59)] = 1837,
  [SMALL_STATE(60)] = 1853,
  [SMALL_STATE(61)] = 1868,
  [SMALL_STATE(62)] = 1883,
  [SMALL_STATE(63)] = 1899,
  [SMALL_STATE(64)] = 1912,
  [SMALL_STATE(65)] = 1925,
  [SMALL_STATE(66)] = 1938,
  [SMALL_STATE(67)] = 1951,
  [SMALL_STATE(68)] = 1964,
  [SMALL_STATE(69)] = 1974,
  [SMALL_STATE(70)] = 1984,
  [SMALL_STATE(71)] = 1992,
  [SMALL_STATE(72)] = 2000,
  [SMALL_STATE(73)] = 2010,
  [SMALL_STATE(74)] = 2020,
  [SMALL_STATE(75)] = 2028,
  [SMALL_STATE(76)] = 2035,
  [SMALL_STATE(77)] = 2042,
  [SMALL_STATE(78)] = 2049,
  [SMALL_STATE(79)] = 2056,
  [SMALL_STATE(80)] = 2063,
  [SMALL_STATE(81)] = 2070,
  [SMALL_STATE(82)] = 2077,
  [SMALL_STATE(83)] = 2084,
  [SMALL_STATE(84)] = 2091,
  [SMALL_STATE(85)] = 2098,
  [SMALL_STATE(86)] = 2105,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_reference, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_reference, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_expression, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_expression, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_expression, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_expression, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_expression, 3, 0, 3),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_expression, 3, 0, 3),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_expression, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_expression, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 3, 0, 4),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 3, 0, 4),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_expression, 3, 0, 5),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expression, 3, 0, 5),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 4, 0, 9),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 6),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 6),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, 0, 7),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5, 0, 10),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 5, 0, 11),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 6, 0, 12),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_expression, 4, 0, 8),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_expression, 4, 0, 8),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [191] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 3, 0, 1),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 6, 0, 2),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 5, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tt(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
