#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 71
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 13

enum ts_symbol_identifiers {
  anon_sym_fn = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_EQ = 4,
  anon_sym_SEMI = 5,
  sym_identifier = 6,
  sym_number = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  anon_sym_BANG_EQ = 10,
  anon_sym_EQ_EQ = 11,
  anon_sym_LT = 12,
  anon_sym_LT_EQ = 13,
  anon_sym_GT = 14,
  anon_sym_GT_EQ = 15,
  anon_sym_PLUS = 16,
  anon_sym_DASH = 17,
  anon_sym_STAR = 18,
  anon_sym_SLASH = 19,
  anon_sym_COLON = 20,
  anon_sym_LBRACE = 21,
  anon_sym_RBRACE = 22,
  anon_sym_if = 23,
  anon_sym_in = 24,
  anon_sym_else = 25,
  sym_program = 26,
  sym__declaration = 27,
  sym_function_declaration = 28,
  sym__expression = 29,
  sym_boolean = 30,
  sym_binary_expression = 31,
  sym_assignment_expression = 32,
  sym_variable_reference = 33,
  sym_variable_declaration = 34,
  sym_grouped_expression = 35,
  sym_block_expression = 36,
  sym_if_expression = 37,
  aux_sym_block_expression_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if",
  [anon_sym_in] = "in",
  [anon_sym_else] = "else",
  [sym_program] = "program",
  [sym__declaration] = "_declaration",
  [sym_function_declaration] = "function_declaration",
  [sym__expression] = "_expression",
  [sym_boolean] = "boolean",
  [sym_binary_expression] = "binary_expression",
  [sym_assignment_expression] = "assignment_expression",
  [sym_variable_reference] = "variable_reference",
  [sym_variable_declaration] = "variable_declaration",
  [sym_grouped_expression] = "grouped_expression",
  [sym_block_expression] = "block_expression",
  [sym_if_expression] = "if_expression",
  [aux_sym_block_expression_repeat1] = "block_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_else] = anon_sym_else,
  [sym_program] = sym_program,
  [sym__declaration] = sym__declaration,
  [sym_function_declaration] = sym_function_declaration,
  [sym__expression] = sym__expression,
  [sym_boolean] = sym_boolean,
  [sym_binary_expression] = sym_binary_expression,
  [sym_assignment_expression] = sym_assignment_expression,
  [sym_variable_reference] = sym_variable_reference,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_grouped_expression] = sym_grouped_expression,
  [sym_block_expression] = sym_block_expression,
  [sym_if_expression] = sym_if_expression,
  [aux_sym_block_expression_repeat1] = aux_sym_block_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_grouped_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_block_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_block_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_condition = 1,
  field_else = 2,
  field_identifier = 3,
  field_initializing_expression = 4,
  field_lhs = 5,
  field_name = 6,
  field_operator = 7,
  field_return_expression = 8,
  field_rhs = 9,
  field_then = 10,
  field_type = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
  [field_else] = "else",
  [field_identifier] = "identifier",
  [field_initializing_expression] = "initializing_expression",
  [field_lhs] = "lhs",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_return_expression] = "return_expression",
  [field_rhs] = "rhs",
  [field_then] = "then",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 1},
  [9] = {.index = 11, .length = 2},
  [10] = {.index = 13, .length = 3},
  [11] = {.index = 16, .length = 4},
  [12] = {.index = 20, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_identifier, 0},
  [1] =
    {field_name, 1},
  [2] =
    {field_return_expression, 1},
  [3] =
    {field_condition, 1},
    {field_then, 2},
  [5] =
    {field_lhs, 0},
    {field_rhs, 2},
  [7] =
    {field_operator, 1},
  [8] =
    {field_initializing_expression, 3},
    {field_name, 0},
  [10] =
    {field_return_expression, 2},
  [11] =
    {field_condition, 1},
    {field_then, 3},
  [13] =
    {field_initializing_expression, 4},
    {field_name, 0},
    {field_type, 2},
  [16] =
    {field_condition, 1},
    {field_else, 3},
    {field_else, 4},
    {field_then, 2},
  [20] =
    {field_condition, 1},
    {field_else, 4},
    {field_else, 5},
    {field_then, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 14,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 12,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 19,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 17,
  [31] = 18,
  [32] = 32,
  [33] = 23,
  [34] = 34,
  [35] = 35,
  [36] = 21,
  [37] = 37,
  [38] = 22,
  [39] = 24,
  [40] = 29,
  [41] = 32,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 26,
  [46] = 46,
  [47] = 42,
  [48] = 34,
  [49] = 43,
  [50] = 44,
  [51] = 46,
  [52] = 52,
  [53] = 52,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 60,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 67,
  [70] = 70,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '!', 2,
        '(', 17,
        ')', 18,
        '*', 44,
        '+', 42,
        '-', 43,
        '/', 45,
        ':', 46,
        ';', 21,
        '<', 38,
        '=', 20,
        '>', 40,
        'e', 9,
        'f', 4,
        'i', 8,
        't', 11,
        '{', 47,
        '}', 48,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == 'f') ADVANCE(22);
      if (lookahead == 'i') ADVANCE(25);
      if (lookahead == 't') ADVANCE(27);
      if (lookahead == '{') ADVANCE(47);
      if (lookahead == '}') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(36);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(10);
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(49);
      if (lookahead == 'n') ADVANCE(51);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(5);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(37);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(63),
    [sym__declaration] = STATE(64),
    [sym_function_declaration] = STATE(64),
    [anon_sym_fn] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      sym_number,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    STATE(3), 1,
      aux_sym_block_expression_repeat1,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [37] = 9,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_block_expression_repeat1,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(54), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [74] = 9,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(26), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(38), 1,
      anon_sym_RBRACE,
    ACTIONS(40), 1,
      anon_sym_if,
    STATE(4), 1,
      aux_sym_block_expression_repeat1,
    ACTIONS(32), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(58), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [111] = 3,
    ACTIONS(47), 1,
      anon_sym_COLON,
    ACTIONS(45), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(43), 14,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [136] = 3,
    ACTIONS(49), 1,
      anon_sym_COLON,
    ACTIONS(45), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(43), 13,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [160] = 2,
    ACTIONS(53), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(51), 14,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [182] = 2,
    ACTIONS(57), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(55), 14,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [204] = 2,
    ACTIONS(61), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 14,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [226] = 2,
    ACTIONS(65), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(63), 14,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [248] = 2,
    ACTIONS(69), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 14,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [270] = 3,
    ACTIONS(75), 1,
      anon_sym_else,
    ACTIONS(73), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(71), 13,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [294] = 2,
    ACTIONS(79), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 14,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [316] = 7,
    ACTIONS(83), 1,
      anon_sym_EQ,
    ACTIONS(93), 1,
      anon_sym_else,
    ACTIONS(87), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(85), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 5,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [348] = 2,
    ACTIONS(97), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 14,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [370] = 6,
    ACTIONS(83), 1,
      anon_sym_EQ,
    ACTIONS(87), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(85), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(81), 6,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [400] = 5,
    ACTIONS(83), 1,
      anon_sym_EQ,
    ACTIONS(89), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(101), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(99), 10,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [428] = 4,
    ACTIONS(83), 1,
      anon_sym_EQ,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(101), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(99), 12,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [454] = 3,
    ACTIONS(83), 1,
      anon_sym_EQ,
    ACTIONS(101), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(99), 14,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [478] = 2,
    ACTIONS(73), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(71), 14,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [500] = 6,
    ACTIONS(83), 1,
      anon_sym_EQ,
    ACTIONS(87), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(85), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(103), 6,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [530] = 6,
    ACTIONS(83), 1,
      anon_sym_EQ,
    ACTIONS(87), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(85), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(105), 6,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [560] = 6,
    ACTIONS(83), 1,
      anon_sym_EQ,
    ACTIONS(87), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(85), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(107), 6,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [590] = 6,
    ACTIONS(83), 1,
      anon_sym_EQ,
    ACTIONS(87), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(85), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(109), 6,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
      anon_sym_else,
  [620] = 3,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(101), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(99), 13,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [643] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(113), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [674] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(115), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(57), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [705] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(117), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(56), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [736] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(121), 1,
      sym_number,
    ACTIONS(123), 1,
      anon_sym_if,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(14), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [767] = 5,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(101), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(127), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(99), 9,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [794] = 4,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(101), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(127), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(99), 11,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [819] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(129), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [850] = 6,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(127), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(107), 5,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [879] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(135), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [910] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(137), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [941] = 6,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(127), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(103), 5,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [970] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(139), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(39), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1001] = 6,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(127), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(105), 5,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [1030] = 6,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(127), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(109), 5,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_in,
  [1059] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(123), 1,
      anon_sym_if,
    ACTIONS(141), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(16), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1090] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(143), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(53), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1121] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(123), 1,
      anon_sym_if,
    ACTIONS(145), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(13), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1152] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(123), 1,
      anon_sym_if,
    ACTIONS(147), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1183] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(123), 1,
      anon_sym_if,
    ACTIONS(149), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(18), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1214] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(123), 1,
      anon_sym_if,
    ACTIONS(151), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(19), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1245] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(123), 1,
      anon_sym_if,
    ACTIONS(153), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(23), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1276] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(145), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(13), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1307] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(123), 1,
      anon_sym_if,
    ACTIONS(155), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1338] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(157), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1369] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(31), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1400] = 7,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(161), 1,
      sym_number,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 9,
      sym__expression,
      sym_boolean,
      sym_binary_expression,
      sym_assignment_expression,
      sym_variable_reference,
      sym_variable_declaration,
      sym_grouped_expression,
      sym_block_expression,
      sym_if_expression,
  [1431] = 8,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(163), 1,
      anon_sym_in,
    STATE(12), 1,
      sym_block_expression,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(127), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1462] = 8,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(165), 1,
      anon_sym_in,
    STATE(20), 1,
      sym_block_expression,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(127), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1493] = 7,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(167), 1,
      anon_sym_SEMI,
    ACTIONS(169), 1,
      anon_sym_RBRACE,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(127), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1521] = 7,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(167), 1,
      anon_sym_SEMI,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(127), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1549] = 6,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(127), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1574] = 6,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(175), 1,
      anon_sym_SEMI,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(127), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1599] = 6,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(167), 1,
      anon_sym_SEMI,
    ACTIONS(125), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(127), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 4,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1624] = 2,
    ACTIONS(38), 4,
      anon_sym_LPAREN,
      sym_number,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(177), 4,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_if,
  [1637] = 2,
    ACTIONS(179), 1,
      anon_sym_EQ,
    ACTIONS(181), 1,
      sym_identifier,
  [1644] = 2,
    ACTIONS(183), 1,
      anon_sym_EQ,
    ACTIONS(185), 1,
      sym_identifier,
  [1651] = 1,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
  [1655] = 1,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
  [1659] = 1,
    ACTIONS(191), 1,
      ts_builtin_sym_end,
  [1663] = 1,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
  [1667] = 1,
    ACTIONS(195), 1,
      sym_identifier,
  [1671] = 1,
    ACTIONS(197), 1,
      anon_sym_EQ,
  [1675] = 1,
    ACTIONS(199), 1,
      anon_sym_EQ,
  [1679] = 1,
    ACTIONS(201), 1,
      anon_sym_EQ,
  [1683] = 1,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 111,
  [SMALL_STATE(6)] = 136,
  [SMALL_STATE(7)] = 160,
  [SMALL_STATE(8)] = 182,
  [SMALL_STATE(9)] = 204,
  [SMALL_STATE(10)] = 226,
  [SMALL_STATE(11)] = 248,
  [SMALL_STATE(12)] = 270,
  [SMALL_STATE(13)] = 294,
  [SMALL_STATE(14)] = 316,
  [SMALL_STATE(15)] = 348,
  [SMALL_STATE(16)] = 370,
  [SMALL_STATE(17)] = 400,
  [SMALL_STATE(18)] = 428,
  [SMALL_STATE(19)] = 454,
  [SMALL_STATE(20)] = 478,
  [SMALL_STATE(21)] = 500,
  [SMALL_STATE(22)] = 530,
  [SMALL_STATE(23)] = 560,
  [SMALL_STATE(24)] = 590,
  [SMALL_STATE(25)] = 620,
  [SMALL_STATE(26)] = 643,
  [SMALL_STATE(27)] = 674,
  [SMALL_STATE(28)] = 705,
  [SMALL_STATE(29)] = 736,
  [SMALL_STATE(30)] = 767,
  [SMALL_STATE(31)] = 794,
  [SMALL_STATE(32)] = 819,
  [SMALL_STATE(33)] = 850,
  [SMALL_STATE(34)] = 879,
  [SMALL_STATE(35)] = 910,
  [SMALL_STATE(36)] = 941,
  [SMALL_STATE(37)] = 970,
  [SMALL_STATE(38)] = 1001,
  [SMALL_STATE(39)] = 1030,
  [SMALL_STATE(40)] = 1059,
  [SMALL_STATE(41)] = 1090,
  [SMALL_STATE(42)] = 1121,
  [SMALL_STATE(43)] = 1152,
  [SMALL_STATE(44)] = 1183,
  [SMALL_STATE(45)] = 1214,
  [SMALL_STATE(46)] = 1245,
  [SMALL_STATE(47)] = 1276,
  [SMALL_STATE(48)] = 1307,
  [SMALL_STATE(49)] = 1338,
  [SMALL_STATE(50)] = 1369,
  [SMALL_STATE(51)] = 1400,
  [SMALL_STATE(52)] = 1431,
  [SMALL_STATE(53)] = 1462,
  [SMALL_STATE(54)] = 1493,
  [SMALL_STATE(55)] = 1521,
  [SMALL_STATE(56)] = 1549,
  [SMALL_STATE(57)] = 1574,
  [SMALL_STATE(58)] = 1599,
  [SMALL_STATE(59)] = 1624,
  [SMALL_STATE(60)] = 1637,
  [SMALL_STATE(61)] = 1644,
  [SMALL_STATE(62)] = 1651,
  [SMALL_STATE(63)] = 1655,
  [SMALL_STATE(64)] = 1659,
  [SMALL_STATE(65)] = 1663,
  [SMALL_STATE(66)] = 1667,
  [SMALL_STATE(67)] = 1671,
  [SMALL_STATE(68)] = 1675,
  [SMALL_STATE(69)] = 1679,
  [SMALL_STATE(70)] = 1683,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_reference, 1, 0, 1),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_reference, 1, 0, 1),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_expression, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_expression, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_expression, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_expression, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_expression, 3, 0, 3),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_expression, 3, 0, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_expression, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_expression, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 3, 0, 4),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 3, 0, 4),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expression, 3, 0, 5),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_expression, 3, 0, 5),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 4, 0, 9),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_expression, 4, 0, 8),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_expression, 4, 0, 8),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 6),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 6),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5, 0, 10),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 5, 0, 11),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, 0, 7),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 6, 0, 12),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_expression_repeat1, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [189] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 7, 0, 2),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tt(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
